#!/bin/bash -f


for b in 3 9 13 27
do
	filename=n_k_b${b}_GPU.txt
	echo  $filename
	for N in 1000000
	do
		echo "" >> ${filename}
		echo "  #Data " >> ${filename}
		echo "" >> ${filename}
         	./MatrixPowers${b} ${N} Benchmarks/band${b}_n_${N}.mtx >> ${filename}
	done
done


